version: '3.9'

services:
    mapleserver2_docs:
        container_name: mapleserver2_docs
        image: mapleserver2_docs
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
            args:
                ENV: ${NODE_ENV}
        volumes:
            - ./logs:/var/log/nginx
        environment:
            DOCKER: 'true'
        expose:
            - '${PORT}'
        networks:
            - docker

networks:
    docker:
        external: true
