name: Test Pull Request

on:
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v2.2.4
              with:
                version: 6.0.2
            - run: pnpm install
            - run: pnpm build